### ISSUE TITLE
Todos needed

### ISSUE THREAD

**Issue by OlegTheCat** [alexkehayias/chocolatier#4]
Hi.

It would be nice to have list of features that should be implemented in order to get chocolatier out of WIP state. Probably they should be listed in README or github issue should be opened for each missing feature.

What do you think about this?

**Comment by alexkehayias** [comment]
Sounds good, thanks for the feedback I will add one soon!

**Comment by alexkehayias** [comment]
I've added the todo.org file I've been using for this project. At the top is the releases. I would consider this  project to be useful for other people to build off of and contribute once 0.2.0 checklist is completed. It's mainly cleaning up verbose syntax with macros and performance related.

**Comment by OlegTheCat** [comment]
Thank you for response. BTW, would you mind if I tried to implement text rendering component? Seems it is good task to try engine in action and understand how it works under the hood.

**Comment by alexkehayias** [comment]
Yes of course! I would take a quick look through the pixijs docs. I haven't wrapped text rendering yet, but you can add it to `chocolatier.engine.pixi`. Let me know if you have any questions alex.kehayias <at> gmail.

**Comment by OlegTheCat** [comment]
Ok, thanks!
