### ISSUE TITLE
Cannot load chocolatier.core namespace

### ISSUE THREAD

**Issue by niamu** [alexkehayias/chocolatier#5]
Maybe I'm doing something wrong (I am fairly new to ClojureScript), but I can't seem to properly load ```chocolatier.core``` namespace after the browser repl loads.

> cljs.user=> (load "chocolatier/core")
> WARNING: Use of undeclared Var cljs.user/load at line 1 <cljs repl>
>#\<TypeError: undefined is not an object (evaluating 'cljs.user.load.call')\>

>eval code
>eval@[native code]
>http://127.0.0.1:9000/app:2018:317
>evaluate_javascript@http://127.0.0.1:9000/app:2019:236
>http://127.0.0.1:9000/app:2027:113
>deliver@http://127.0.0.1:9000/app:1883:278
>xpcDeliver@http://127.0.0.1:9000/app:1950:366
>messageReceived_@http://127.0.0.1:9000/app:1906:408
>fireListener@http://127.0.0.1:9000/app:1523:130
>handleBrowserEvent_@http://127.0.0.1:9000/app:1526:198
>http://127.0.0.1:9000/app:1515:401
>nil

The browser repl functions normally as I have tested it by sending ```(js/alert 'test')```. I just can't seem to get past the last step where I can call ```(restart-game!)```.

**Comment by alexkehayias** [comment]
You are trying to call a function which does not exist. I believe you are looking for the function `load-file` or `load-namespace`. I'm using cider with emacs which is a great interactive environment for connecting with the browser repl. 

Closing since this isn't an issue, but if you need help feel free to keep commenting here.

**Comment by kitofr** [comment]
I suppose (cause I can't really understand the REAME either) that what @niamu is looking for is a better description on what you mean by "load".

I was trying:

`$ lein repl`
```clojure
user=> (use 'chocolatier.server)
nil
user=> (restart-server!)
;.... loads of warnings
```

Navigate to `http://localhost:9000/app`

```clojure
cljs.user=> (use 'chocolatier.core)
WARNING: Use of undeclared Var cljs.user/use at line 1 <cljs repl>
#<TypeError: Cannot read property 'call' of undefined>
TypeError: Cannot read property 'call' of undefined
    at eval (repl-1427627181980.js:1:82)
    at eval (repl-1427627181980.js:13:4)
    at http://localhost:9000/app:2043:313
    at clojure.browser.repl.evaluate_javascript (http://localhost:9000/app:2044:236)
    at Object.callback (http://localhost:9000/app:2052:109)
    at goog.messaging.AbstractChannel.deliver (http://localhost:9000/app:1908:270)
    at goog.net.xpc.CrossPageChannel.xpcDeliver (http://localhost:9000/app:1975:372)
    at Function.goog.net.xpc.NativeMessagingTransport.messageReceived_ (http://localhost:9000/app:1931:398)
    at Object.goog.events.fireListener (http://localhost:9000/app:1548:126)
    at goog.events.handleBrowserEvent_ (http://localhost:9000/app:1551:186)
nil
```

And `(restart-game!)` yields the same thing.

**Comment by alexkehayias** [comment]
The loads of warnings were introduced at some point when updating to the latest version of clojurescript. You need to hit enter after all of that to proceed for some reason. The following works for me:

```
lein repl
;; Wait for the repl to start
(in-ns 'chocolatier.server)
(load-file "chocolatier.server")
(restart-server!)
;; Wait for warnings to finish
;; Hit enter/return
(in-ns 'chocolatier.core)
(load-file "chocolatier.core")
(restart-game!)
```

I do still recommend you use cider in emacs to do development, but the principles are the same. Change namespace, load the file, call the function you want.

I'll open up an issue about the excessive error logging.

**Comment by kitofr** [comment]
Oh, nice. I'll try that out.

Btw, I'm using `Vim/VimClojure/fireplace` combo, which works fine. I also imagine that plp are using lighttable.
